{
 "title": "Cisco CX3560",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sysname",
    "label": "SysName",
    "query": "show tag values from ciscoInterface with key = \"sysName\""
   },
   {
    "name": "Interface",
    "query": "show tag values from ciscoInterface with key = \"ifDescr\" where sysName=~/$sysname/"
   },
   {
    "name": "PhysEntity",
    "query": "show tag values from ciscoPhysEntity with key = \"ifDescr\" where sysName=~/$sysname/"
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Product",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "snmp",
       "select": [
        [
         { "params": [ "ciscoProduct" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=", "value": "cx.home" }
       ]
      }
     ]
    },
    {
     "title": "IOS Featureset",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "snmp",
       "select": [
        [
         { "params": [ "ciscoSoftware" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=", "value": "cx.home" }
       ]
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "5sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ciscoCPU",
       "select": [
        [
         { "params": [ "cpmCPUTotal5secRev" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" }
       ]
      },
      {
       "alias": "1min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ciscoCPU",
       "select": [
        [
         { "params": [ "cpmCPUTotal1minRev" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" }
       ]
      },
      {
       "alias": "5min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ciscoCPU",
       "select": [
        [
         { "params": [ "cpmCPUTotal5minRev" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=", "value": "cx.home" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ciscoEnvMonTemperatureStatusTable",
       "select": [
        [
         {
          "params": [
           "ciscoEnvMonTemperatureStatusValue"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" }
       ]
      }
     ]
    },
    {
     "title": "Powersupply Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "ciscoEnvMonSupplyStatusTable",
       "select": [
        [
         { "params": [ "ciscoEnvMonSupplyStatusDescr" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" }
       ]
      }
     ]
    },
    {
     "title": "TemperatureStatus",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "ciscoEnvMonTemperatureStatusTable",
       "select": [
        [
         {
          "params": [
           "ciscoEnvMonTemperatureStatusDescr"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Interface Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$Interface",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "repeat": "Interface",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Transceiver Status $PhysEntity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "PhysEntity",
   "collapsed": true
  },
  {
   "title": "Bias Currrent Sensor",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "mamp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ciscoPhysEntity",
     "select": [
      [
       { "params": [ "entSensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$PhysEntity$/" },
      { "condition": "AND", "key": "sensorDescr", "operator": "=", "value": "Bias Current Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Module Temperature Sensor",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ciscoPhysEntity",
     "select": [
      [
       { "params": [ "entSensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$PhysEntity$/" },
      { "condition": "AND", "key": "sensorDescr", "operator": "=", "value": "Module Temperature Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Optical Rx Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "format": "dBm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ciscoPhysEntity",
     "select": [
      [
       { "params": [ "entSensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$PhysEntity$/" },
      { "condition": "AND", "key": "sensorDescr", "operator": "=", "value": "Receive Power Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Optical Tx Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "format": "dBm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ciscoPhysEntity",
     "select": [
      [
       { "params": [ "entSensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$PhysEntity$/" },
      { "condition": "AND", "key": "sensorDescr", "operator": "=", "value": "Transmit Power Sensor" }
     ]
    }
   ]
  },
  {
   "title": "Optical Tx Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ciscoPhysEntity",
     "select": [
      [
       { "params": [ "entSensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$PhysEntity$/" },
      { "condition": "AND", "key": "sensorDescr", "operator": "=", "value": "Supply Voltage Sensor" }
     ]
    }
   ]
  },
  { "title": "Interface Status $Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "Interface" },
  {
   "title": "OperStatus",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  },
  {
   "title": "$Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "ifHCInOctets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    },
    {
     "alias": "ifHCOutOctets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    },
    {
     "alias": "ifInErrors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    },
    {
     "alias": "ifOutErrors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "Gbits",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ciscoInterface",
     "select": [
      [
       { "params": [ "ifLastChange" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$sysname$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  }
 ]
}